services:
  db:
    image: postgres:18
    restart: no 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movieservice 
    ports:
      - "5433:5432"
    volumes:
      - movieservice:/var/lib/postgresql/18/docker
  cache:
    image: redis:alpine
    restart: no
    container_name: redis-cache
    ports:
      - "6379:6379"
    # command: redis-server --save 60 1 --loglevel warning
    # TODO: Add all services
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
    #   interval: 10s
    #   retries: 5
    #   start_period: 30s
    #   timeout: 10s 
  # backend:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
volumes:
  movieservice:
